create table if not exists public.leaderboard_entries (
  id bigint generated by default as identity primary key,
  player_id text not null,
  player_name text not null check (char_length(player_name) between 1 and 32),
  score integer not null check (score >= 0),
  question_count integer not null check (question_count > 0),
  accuracy numeric not null check (accuracy >= 0 and accuracy <= 100),
  module text not null,
  completed_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists leaderboard_entries_score_idx
  on public.leaderboard_entries (score desc, accuracy desc, completed_at desc);

alter table public.leaderboard_entries enable row level security;

drop policy if exists "Public leaderboard read" on public.leaderboard_entries;
create policy "Public leaderboard read"
  on public.leaderboard_entries
  for select
  using (true);

drop policy if exists "Browser leaderboard insert" on public.leaderboard_entries;
create policy "Browser leaderboard insert"
  on public.leaderboard_entries
  for insert
  with check (
    char_length(player_id) between 8 and 80
    and char_length(player_name) between 1 and 32
    and score >= 0
    and question_count between 1 and 300
    and accuracy >= 0
    and accuracy <= 100
  );
